### ISSUE TITLE
Always Error 

### ISSUE THREAD

**Issue by st3xd3v** [Samgisaninja/SuccessionRestore#56] opened 2019-08-28 08:36 UTC
![BB4FAE18-DDA9-4135-A318-8DC76A99188B](https://user-images.githubusercontent.com/34175671/63839461-a3f0af00-c97f-11e9-8778-b5692a9425d2.png)

why do I always get this error?

**Comment by Samgisaninja** [comment] 2019-08-28 16:24
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-08-28 16:24 UTC
