### ISSUE TITLE
Erase iPhone not working

### ISSUE THREAD

**Issue by Antraxs** [Samgisaninja/SuccessionRestore#35] opened 2019-05-28 18:29 UTC
Trying to restore my iPhone but nothing happens when I press “Erase iPhone”. Rebooted multiple time and even downloaded the ipsw.

iPhone 11,6 
iOS 12.1.1
iOS Build 16C50

**Comment by Samgisaninja** [comment] 2019-05-28 18:30
does /var/MobileSoftwareUpdate/mnt1/sbin/launchd exist?

**Comment by Antraxs** [comment] 2019-05-28 18:34
/sbin/launchd does not exist

**Comment by Antraxs** [comment] 2019-05-28 19:14
totally blanked out but nothing happened when the "Mounting filesystem" popup comes up.

**Comment by Samgisaninja** [comment] 2019-05-28 19:43
Duplicate of #28

**Closed as completed by Samgisaninja** 2019-05-28 19:43 UTC
