### ISSUE TITLE
Nothing happens after tapping OK.

### ISSUE THREAD

**Issue by liu-congcong** [Samgisaninja/SuccessionRestore#39] opened 2019-06-07 11:54 UTC
Hi, I have a lot of exams in the past, I am sorry that there is no timely feedback.
Failed  to restore my iPad (12.1.1) using Succession version 1.3.3. Nothing happens after tapping OK. I followed your instructions (mount 'disk4s2s1' to 'mnt1'), and successfully restored my iPad. Then I tried the second time, I met a new problem that was no permission to make the "mnt1" in "MobileSoftwareUpdate", but it was solved with the help of Halo-Michael.
I hope these feedbacks can help you, of course, thank you very much.

**Comment by Samgisaninja** [comment] 2019-06-07 14:40
Duplicate of #29

**Closed as completed by Samgisaninja** 2019-06-07 14:40 UTC
