### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by JustinTsang0772** [Samgisaninja/SuccessionRestore#16] opened 2019-04-23 07:15 UTC
It's been like this, it's not recoverable.
![image](https://user-images.githubusercontent.com/41716319/56562186-782d7900-65db-11e9-954f-0f2101130b04.png)
![2019_04_23_15_13_IMG_0003](https://user-images.githubusercontent.com/41716319/56562094-3e5c7280-65db-11e9-898e-72a0227c3e3d.PNG)
![2019_04_23_15_13_IMG_0003](https://user-images.githubusercontent.com/41716319/56561847-9a72c700-65da-11e9-9660-e527835f9f23.PNG)
![2019_04_23_15_12_IMG_0001](https://user-images.githubusercontent.com/41716319/56561861-a3639880-65da-11e9-8004-f507c996605e.PNG)
![2019_04_23_15_13_IMG_0002](https://user-images.githubusercontent.com/41716319/56561864-a494c580-65da-11e9-81f6-2abedee3f363.PNG)

**Comment by jluo98** [comment] 2019-04-23 13:17
This is a known bug, wait for the next update and try again.

**Comment by Samgisaninja** [comment] 2019-04-23 19:22
Duplicate of #13

**Closed as completed by Samgisaninja** 2019-04-23 19:22 UTC

**Comment by JustinTsang0772** [comment] 2019-04-24 11:30
THX
