### ISSUE TITLE
Succession didn't delete everything related to my jailbreak

### ISSUE THREAD

**Issue by 0n** [Samgisaninja/SuccessionRestore#83] opened 2020-01-02 07:15 UTC
Hi, I used succession and it didn't delete everything I installed using my jailbreak
![IMG_0003 1](https://user-images.githubusercontent.com/45835056/71655622-8fde0500-2d05-11ea-8408-971076517c26.PNG)
![IMG_0002 1](https://user-images.githubusercontent.com/45835056/71655636-9f5d4e00-2d05-11ea-8bc8-caeb068e4954.PNG)

**Comment by 0n** [comment] 2020-01-02 07:16
I'm on an iPhone SE 64gb on iOS 12.1.1, I used unc0ver to jailbreak

**Comment by Samgisaninja** [comment] 2020-01-02 07:16
1. What version of succession did you use
2. Can you re-jailbreak and see if you can open any of those apps?

**Comment by 0n** [comment] 2020-01-03 06:59
Yes I can open them after rejailbreaking, I used Succession 1.4.6 apparently
![IMG_0004 1](https://user-images.githubusercontent.com/45835056/71710930-8b305400-2dcc-11ea-8ed9-0f2f34cb5c5b.PNG)

**Comment by Samgisaninja** [comment] 2020-01-03 07:02
Duplicate of #44

**Closed as completed by Samgisaninja** 2020-01-03 07:02 UTC
