### ISSUE TITLE
Sir when i click in prepare for restore it stuck in wait for 10 seconds

### ISSUE THREAD

**Issue by AhseesMalik** [Samgisaninja/SuccessionRestore#92] opened 2020-02-01 21:59 UTC
Hi there,
Hope you are having a good day.
Sir when i click in prepare for restore it stuck in wait for 10 seconds can you please help me to solve this kind of problem.

**Comment by Samgisaninja** [comment] 2020-02-01 22:00
Duplicate of #89

**Closed as completed by Samgisaninja** 2020-02-01 22:00 UTC
