### ISSUE TITLE
This step might fail...

### ISSUE THREAD

**Issue by grkka** [Samgisaninja/SuccessionRestore#36] opened 2019-05-31 16:03 UTC
![IMG_3427](https://user-images.githubusercontent.com/14794477/58718684-58edec80-83ce-11e9-8756-f31f4c2d8447.png)
iPhone Xs Max iOS 12.1.2

**Comment by Samgisaninja** [comment] 2019-05-31 19:37
duplicate of #28

**Closed as completed by Samgisaninja** 2019-05-31 19:37 UTC
