### ISSUE TITLE
The succdatroot is not supported in ios 9.3.3 with pangu jailbreak because the dylib does not exist

### ISSUE THREAD

**Issue by kocoman1** [Samgisaninja/SuccessionRestore#137] opened 2020-09-04 21:45 UTC

**Comment by Oakman312** [comment] 2020-09-17 00:00
I am having the same issue here on an iPhone 6 on iOS 9.3.2. Succession immediately crashes when I try to open it.

**Comment by kocoman1** [comment] 2020-09-17 07:35
Dont restore you will get stuck at activation screen

**Comment by Samgisaninja** [comment] 2020-11-26 23:22
Duplicate of #133

**Closed as completed by Samgisaninja** 2020-11-26 23:22 UTC
