### ISSUE TITLE
Stuck after pressing Go iphone 8 ios 12.1.2

### ISSUE THREAD

**Issue by Ringwraith1of9** [Samgisaninja/SuccessionRestore#43] opened 2019-07-12 03:02 UTC
When I press go I get no further.Copy of log file if it helps.

[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:48 +0000] Line 31: RestoreViewController has loaded!
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 189: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 193: Read fstab! /dev/disk0s1s1 / apfs ro 0 1
/dev/disk0s1s2 /private/var apfs rw,nosuid,nodev 0 2
/dev/disk0s1s3 /private/var/wireless/baseband_data apfs rw,nosuid,nodev,nobrowse 0 2

[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 200: Identified filesystem type as APFS! apfs
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 211: attachRestoreDisk called!
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 216: attach returned 5
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:49 +0000] Line 218: attached to  aka 
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 70: startRestoreButtonAction called
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 109: no apfs snapshot operations requested
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 115: showRestoreAlert called!
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 148: Filesystem is not mounted, showing mount alert now
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 153: mountingAlert handler called, identified theDiskString as 
[SUCCESSIONLOG 1.3.4: 2019-07-12 02:52:50 +0000] Line 542: ERROR! unable to identify theDisk, neither s2s1 or s2 existed

**Comment by Samgisaninja** [comment] 2019-07-12 03:03
duplicate of #37

**Closed as completed by Samgisaninja** 2019-07-12 03:03 UTC
