### ISSUE TITLE
Mounting please wait ...   stuck

### ISSUE THREAD

**Issue by andy72630** [Samgisaninja/SuccessionRestore#74] opened 2019-11-13 10:11 UTC
![86CC8C68-9FA8-467B-937E-DDD8394F707D](https://user-images.githubusercontent.com/26477445/68753997-59e2a580-061f-11ea-86d7-095a4fa77681.png)
as I mentioned in title,the app stuck on the screen as this screen shot

**Comment by andy72630** [comment] 2019-11-13 10:17
https://www.dropbox.com/s/l6ux4w21kw5ns01/succession.log?dl=0

**Comment by the-thz** [comment] 2019-11-18 08:18
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/3857450/succession.log)
Same problem. iPhone X, 13.1.3

**Comment by jonayh** [comment] 2019-11-18 23:07
close and retry

**Comment by kevan1** [comment] 2019-11-19 14:24
same problem, iPhone Xs Max 12.4
log:

**Comment by kevan1** [comment] 2019-11-19 14:24
same problem, iPhone Xs Max 12.4
log:
[SUCCESSIONLOG 1.4.3: 2019-11-19 14:19:49 +0000] Line 268: hdik output is: 
[SUCCESSIONLOG 1.4.3: 2019-11-19 14:19:49 +0000] Line 255: attachRestoreDisk called!
[SUCCESSIONLOG 1.4.3: 2019-11-19 14:19:49 +0000] Line 263: Using hdik for attach
x25

**Comment by FaisalBiyari** [comment] 2019-11-22 14:24
I found a simple solution

Settings -> General -> About -> Name

Change the name to a simple OneWord

Mine was at "Faisal Biyari's iPhone"
Changed to DiPhoneX, and it worked after that.

I don't know if it's the space, the apostrophe, or the simple act of "set up as New Phone" process. All that matters is that I was able to IMMEDIATELY restore after changing that name.

Edit:
iPhone X - 10,6 - iOS 12.4

**Comment by sharklatan** [comment] 2019-11-26 08:44
Same error 13.2.3 

2 hours Mounting please wait

**Comment by metriics** [comment] 2019-11-29 21:21
I'm on an iPhone XS on 12.4 and am having the same/a similar issue. The log shows the same out at @kevan1 repeated many many times per second. I tried the solution @FaisalBiyari posted, however my phone's name was already one word with no spaces or punctuation and setting it to 'Test' without the apostrophes made no difference either. 

My log can be found here in case the dev is interested in looking at it.
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/3906393/succession.log)

**Comment by ChipSkylark37** [comment] 2019-11-30 16:03
Confirming the same issue regarding mounting on 1.4.3. Renaming didn’t resolve as well as a few reboots. 

This is on an iPhone 6s. 

[Succession.log](https://www.dropbox.com/s/njob715phjibjds/succession.log?dl=0)

**Comment by metriics** [comment] 2019-11-30 17:04
Alright so last night I was able to use succession successfully. What I did was uninstall 1.4.3 from Cydia, then I downloaded the 1.4.2 deb from the releases tab here and installed in using Filza. After that I had no issues mounting. The restore was all good as well. I also did not have the issue of Cydia staying on the homescreen. @ChipSkylark37 that solution might be worth a try.

As a side note, I also successfully updated from 12.4 to 13.2.3 using iTunes (not OTA!) on my XS without data loss if that is what some of you are wanting to do.

Edit: My phone was also named with one word at the time so it's possible that @FaisalBiyari's fix works on 1.4.2. It didn't work on 1.4.3 for me. Just wanted to mention it in case 1.4.2 was still not working for some people after downgrading to it.

**Comment by ChipSkylark37** [comment] 2019-12-01 01:34
@metriics 

Thank you - that worked! Still curious as to why 1.4.3 didn’t work since this was noted to be fixed in 1.4.2 and earlier versions.

**Comment by metriics** [comment] 2019-12-01 20:27
@ChipSkylark37 I wonder if 1.4.3 is supposed to have been pulled? Since it's not even in the releases tab here... Maybe the repos haven't removed it yet. Anyway, to anyone who is having this issue try installing the 1.4.2 deb from the [Releases](https://github.com/Samgisaninja/SuccessionRestore/releases) tab of this git repo using Filza. Make sure to uninstall any other version installed using Cydia first. Should work fine after that.

See this comment for more details: https://github.com/Samgisaninja/SuccessionRestore/issues/74#issuecomment-559996363

**Comment by appleguru** [comment] 2019-12-20 14:49
I had this same issue on 1.4.4 from Cydia. Downgraded to 1.4.3 and it actually seems to be working now...

**Comment by SurceBeats** [comment] 2019-12-22 04:09
I can confirm the following thing

> @ChipSkylark37 I wonder if 1.4.3 is supposed to have been pulled? Since it's not even in the releases tab here... Maybe the repos haven't removed it yet. Anyway, to anyone who is having this issue try installing the 1.4.2 deb from the [Releases](https://github.com/Samgisaninja/SuccessionRestore/releases) tab of this git repo using Filza. Make sure to uninstall any other version installed using Cydia first. Should work fine after that.
> 
> See this comment for more details: [#74 (comment)](https://github.com/Samgisaninja/SuccessionRestore/issues/74#issuecomment-559996363)

1.4.2 worked, had to install the .deb via SSH, for those noobs, got stuck on Mounting please wait for a while and then after 30 seconds another screen came up saying something like Erase iPhone.

Thanks

**Comment by Samgisaninja** [comment] 2019-12-23 02:54
this was **finally** fixed in 1.4.5 by properly using multithreading

**Closed as completed by Samgisaninja** 2019-12-23 02:54 UTC
