### ISSUE TITLE
Error Attaching image failed because hdik returned no output

### ISSUE THREAD

**Issue by kitoep** [Samgisaninja/SuccessionRestore#52] opened 2019-08-21 02:26 UTC
I am on iphone x ios 12.1.2 and after i tap on prepare for restore y got the following message: 

Error Attaching image failed because hdik returned no output

**Comment by Samgisaninja** [comment] 2019-08-21 06:02
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-08-21 06:02 UTC

**Comment by DeniMKD** [comment] 2019-09-08 23:32
How can I fix this
Error Attaching image failed because hdik returned no output
