### ISSUE TITLE
Succession not restoring device after ui cache reboot 

### ISSUE THREAD

**Issue by chaqti** [Samgisaninja/SuccessionRestore#103] opened 2020-02-13 18:08 UTC
After it geos to the ui cache screen on succession it reboots then goes back to its normal state doesn't restore to the chosen firmware 13.2.3. I'm on an iPhone x with jailbreak 13.3

**Comment by Samgisaninja** [comment] 2020-02-13 18:09
Duplicate of #44

**Closed as completed by Samgisaninja** 2020-02-13 18:09 UTC
