### ISSUE TITLE
Stuck on Attaching 1.4.11 / iPhone 8 Plus!

### ISSUE THREAD

**Issue by angelstoned** [Samgisaninja/SuccessionRestore#87] opened 2020-01-29 08:23 UTC
Hey, I just upgraded to the latest version and after extracting successfully, when I try to downgrade I’m stuck on this for a long time without any response! Please help
![image](https://user-images.githubusercontent.com/58833833/73339420-c5afd400-4246-11ea-9e53-7bef52c31bf9.jpg)

**Comment by angelstoned** [comment] 2020-01-29 08:25
This is my log!

![image](https://user-images.githubusercontent.com/58833833/73339524-f5f77280-4246-11ea-89ce-72813bbaf00c.jpg)

**Comment by angelstoned** [comment] 2020-01-29 08:26
I honestly don’t know how to give hdik root access since the log says it needs to be run by it. I would really appreciate it if you could help with issue! Thank you 
![image](https://user-images.githubusercontent.com/58833833/73339629-2a6b2e80-4247-11ea-96c6-cc7303cc6658.jpg)

**Comment by angelstoned** [comment] 2020-01-29 08:28
I see that the last line is saying hdik must be fun by root, but I don’t know how to fix it. Please help me fix it. Thank you

**Comment by Samgisaninja** [comment] 2020-01-29 15:56
Duplicate of #84

**Closed as completed by Samgisaninja** 2020-01-29 15:56 UTC

**Comment by angelstoned** [comment] 2020-01-29 20:53
Forgive my newbieness, I am new to all of this even on GitHub. I’m assuming #84 means I have to look at the other post, which I did several times last night and now. I still don’t understand the solution to my problem! 
Do I have to downgrade and try different version? And in my log it keeps saying hdik need to run as root, what does that even mean?

**Comment by Samgisaninja** [comment] 2020-01-29 21:43
Issue 84 is still open, meaning there is no solution. Please continue further discussion in that thread
