### ISSUE TITLE
10 Second Fix 

### ISSUE THREAD

**Issue by imzargam** [Samgisaninja/SuccessionRestore#94] opened 2020-02-02 09:49 UTC

**Comment by Cryptiiiic** [comment] 2020-02-02 20:59
@Zargam94 literally no information given at all, can you not be like this, this help literally nobody, please close this or provide details

**Comment by Samgisaninja** [comment] 2020-02-02 22:00
meh, he provided enough detail.

Duplicate of #89

**Closed as completed by Samgisaninja** 2020-02-02 22:00 UTC
