### ISSUE TITLE
Pressing erase doesn't start anything

### ISSUE THREAD

**Issue by ghost** [Samgisaninja/SuccessionRestore#32] opened 2019-05-20 09:51 UTC
Hi,
I got an issue with Succession 1.3.2, i use an iPhone XS so A12 on iOS 12.1.2 and i want to start on a new clean base without anything for creating a good jailbreak setup that is conveniant for my usage because for the moment it's not what i exactly want anyway.
I doens't touch the settings like "use Test mode" or anything like that just press downloaded the ipsw with the app and use it but when i press erase iphone i got the pop-up about mouting filesystem can fail, but i press ok and nothing happen so is it an issue with my device or with the tweak ?
Thanks in advance for your answer.

**Comment by Samgisaninja** [comment] 2019-05-21 18:25
Can you please turn on “Log output” and run it?

**Comment by ghost** [comment] 2019-05-22 10:19
Hello,
Sorry for the time but i restore my device on 12.3 because apple got to run a diagnostic on my iphone and don't want them too see that i'm jailbreak for warranty so i will do a futurerestore when all is done thanks for the reply.

**Comment by Samgisaninja** [comment] 2019-05-22 15:07
You can’t futurerestore 12.3->12.1.2

**Comment by Samgisaninja** [comment] 2019-05-22 15:09
I’m gonna close this for now since no one else has reported it and the only user who has reported it is going to be waiting a very long time before they can reproduce it... if anyone else has this I’ll reopen

**Closed as completed by Samgisaninja** 2019-05-22 15:09 UTC
