### ISSUE TITLE
stuck on usr/standalone/firmware 

### ISSUE THREAD

**Issue by WayneBishop1** [Samgisaninja/SuccessionRestore#69] opened 2019-10-11 18:03 UTC
I copied the ipsw to the phone but
Every time i try and restore i get stuck on

usr/standalone/firmware/
Rebuilding usr....

I tried downloading the firmware and get the same error only different text
usr/libexec/xpcproxy
Rebuilding usr....

**Comment by Samgisaninja** [comment] 2019-10-12 08:32
Duplicate of #64

**Closed as completed** 2019-10-12 08:32 UTC
