### ISSUE TITLE
attaching image failed bcz hdik returned no output

### ISSUE THREAD

**Issue by latiefahmad** [Samgisaninja/SuccessionRestore#58] opened 2019-09-02 03:53 UTC
how can i solve this message
https://www.dropbox.com/s/w9behvj86zodef5/photo_2019-09-02_10-49-41.jpg?dl=0

i am use succession 1.3.8

**Comment by Samgisaninja** [comment] 2019-09-02 03:53
duplicate of #48

**Closed as completed by Samgisaninja** 2019-09-02 03:53 UTC
