### ISSUE TITLE
restore not starting.

### ISSUE THREAD

**Issue by gbm777** [Samgisaninja/SuccessionRestore#57] opened 2019-08-31 04:27 UTC
![4F24568C-D8F8-41CE-85CF-974517D2E175](https://user-images.githubusercontent.com/35556952/64059234-aa369380-cbea-11e9-9bec-47dace851321.png)

wts wrong with ios 12.4 iphone 6

**Comment by Samgisaninja** [comment] 2019-08-31 20:26
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-08-31 20:26 UTC

**Comment by gbm777** [comment] 2019-09-01 01:14
btw im using newest 1.3.8version
