### ISSUE TITLE
iOS 11.0.3 on Succession 1.3.5 stuck on "Mounting filesystem tap OK to continue"

### ISSUE THREAD

**Issue by maxshcherbina** [Samgisaninja/SuccessionRestore#50] opened 2019-08-19 13:55 UTC
When using Succession 1.3.5 to restore rootFS on 11.0.3, Succession displays "mounting filesystem tap OK to continue". when pressing OK, nothing happens.

Downgrading to 1.3.4 worked perfectly!

Log:

> [SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:19 +0000] Line 27: RestoreViewController has loaded!
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 185: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 189: Read fstab! /dev/disk0s1s1 / apfs ro 0 1
/dev/disk0s1s2 /private/var apfs rw,nosuid,nodev 0 2
/dev/disk0s1s3 /private/var/wireless/baseband_data apfs rw,nosuid,nodev 0 2
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 196: Identified filesystem type as APFS! apfs
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 207: attachRestoreDisk called!
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 218: hdik output is: 
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 220: 
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 222: current line is 
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 66: startRestoreButtonAction called
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 105: no apfs snapshot operations requested
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 111: showRestoreAlert called!
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:20 +0000] Line 144: Filesystem is not mounted, showing mount alert now
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:21 +0000] Line 149: mountingAlert handler called, identified theDiskString as (null)
[SUCCESSIONLOG 1.3.5: 2019-08-19 05:20:21 +0000] Line 554: ERROR! unable to identify theDisk, neither (null) or (null) existed

**Comment by Samgisaninja** [comment] 2019-08-19 13:56
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-08-19 13:56 UTC
