### ISSUE TITLE
iPhone 6 Plus iOS 10.3.3 not working

### ISSUE THREAD

**Issue by tobias38fmsw** [Samgisaninja/SuccessionRestore#62] opened 2019-09-18 01:37 UTC
Hi,

I use an iPhone 6 Plus with iOS 10.3.3 (14G60) and Succession (1.3.8).

when the ipsw file was finished loading. I clicked on "Prepare for restore!" and this error message came up immediately.

**Error Attaching image failed because hdik returned no output. Please reboot and try again.**

A user on github said to test version 1.3.4 or 1.3.5. What I tried. This time there was no error message and the process started (it looked very good). But then where the message came with rebuild /usr or something.

There it got stuck. I didn't use the device for more than 1 hour and nothing happened. Also restarting and trying again didn't work.

**Comment by tobias38fmsw** [comment] 2019-09-18 01:56
![](https://i.imgur.com/jYXdGeg.jpg)

**Comment by tobias38fmsw** [comment] 2019-09-18 01:58
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:05 +0000] Line 32: RestoreViewController has loaded!
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 190: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 194: Read fstab! /dev/disk0s1s1 / apfs ro 0 1
/dev/disk0s1s2 /private/var apfs rw,nosuid,nodev 0 2
/dev/disk0s1s3 /private/var/wireless/baseband_data apfs rw,nosuid,nodev 0 2

[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 201: Identified filesystem type as APFS! apfs
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 212: attachRestoreDisk called!
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 220: Using hdik for attach
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 225: hdik output is: 
[SUCCESSIONLOG 1.3.8: 2019-09-18 01:51:06 +0000] Line 636: ERROR! Attaching image failed because hdik returned no output. Please reboot and try again.

**Comment by Samgisaninja** [comment] 2019-09-18 04:49
hdik returning no output is a duplicate of #48 

system not being restored is a duplicate of #44

**Closed by Samgisaninja** 2019-09-18 04:49 UTC
