### ISSUE TITLE
Can not work on iPad7,5 with ios12.1.1(16C50)

### ISSUE THREAD

**Issue by liu-congcong** [Samgisaninja/SuccessionRestore#28] opened 2019-05-13 02:57 UTC
Version: 12.1.1 (16C50)
Device: iPad7,5
Jailbreak: unc0ver version 3.0.1
Succession Version: 1.3
IPSW: provided or downloaded

I pressed Erase iPhone (at the bottom), then it an alert said “ Mounting Filesystem... “. Then I pressed OK and it still stays in the Erase iPhone screen, not doing anything.
I don’t want to use Restore rootFS because I want to cleanly wipe my iPad.

**Comment by IMS212** [comment] 2019-05-13 02:58
This is a known issue and we are trying to find the solution. On some iPads the button crashes the app and on others it freezers and we do not know the culprit.

**Comment by Packetfahrer** [comment] 2019-05-13 04:08
Same with Iphone 6.2 Version: 11.3.1

**Comment by Samgisaninja** [comment] 2019-05-14 19:50
this has also been reported on an iPhone10,5 and an iPhone9,3, working on it

**Comment by Samgisaninja** [comment] 2019-05-15 02:02
One of my testers is reporting this build works: https://github.com/Samgisaninja/samgisaninja.github.io/blob/1bb6eb1a8d06be7931e274d4db6423995c8e5051/test/debs/com.samgisaninja.successionrestore_1.3.1_iphoneos-arm.deb?raw=true

If y’all could be so kind as to test it that would be much appreciated.

**Comment by clarityzzz** [comment] 2019-05-17 19:55
@Samgisaninja on 1.3 it never mounted the dmg.
On 1.3.1 the dmg gets mounted but the app crashes.
I suppose this happens because as soon as you press Prepare for Restore, the app starts mounting the dmg(you can see a spinning wheel for a very short period), instead of waiting for the press of the Erase button and upon clicking it, unexpected behaviour happens and the app crashes. I might try to debug this later(and if latest master is 1.3.1).
btw no logs anywhere

**Comment by Samgisaninja** [comment] 2019-05-28 19:45
As of 920ac78ad653e1e4b3d7562361c2511e61bfad01 this is strictly a UI issue, will hopefully have this fixed by the end of the day

**Comment by Samgisaninja** [comment] 2019-06-01 14:16
Fixed in 1.3.3

**Comment by clarityzzz** [comment] 2019-06-02 02:49
@Samgisaninja that’s a no, it’s back to square one. Press ok and nothing happens.
[SUCCESSIONLOG 1.3.3: 2019-06-02 02:51:32 +0000] Line 146: mountingAlert handler called, identified theDiskString as /dev/disk6s2s1
[SUCCESSIONLOG 1.3.3: 2019-06-02 02:51:32 +0000] Line 506: ERROR! unable to identify theDisk, neither /dev/disk6s2s1s2s1 or /dev/disk6s2s1s2 existed

**Comment by Samgisaninja** [comment] 2019-06-02 04:52
*sigh* yay

**Comment by clarityzzz** [comment] 2019-07-20 23:04
this is fixed btw @Samgisaninja

**Comment by Samgisaninja** [comment] 2019-07-21 16:10
eh, idk about that #37

**Closed as completed by Samgisaninja** 2019-07-21 16:10 UTC
