### ISSUE TITLE
succession error ios 12.4 on iphoneX

### ISSUE THREAD

**Issue by b1passfrp** [Samgisaninja/SuccessionRestore#61] opened 2019-09-07 07:18 UTC
today I want to try succession to recover my device, after waiting for the software download and extract, I get a message like this.
`[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:16 +0000] Line 32: RestoreViewController has loaded!
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 190: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 194: Read fstab! /dev/disk0s1s1 / apfs ro 0 1
/dev/disk0s1s2 /private/var apfs rw,nosuid,nodev 0 2
/dev/disk0s1s3 /private/var/wireless/baseband_data apfs rw,nosuid,nodev,nobrowse 0 2
/dev/disk0s1s4 /private/var/hardware apfs rw,nosuid,nodev,nobrowse 0 2

[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 201: Identified filesystem type as APFS! apfs
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 212: attachRestoreDisk called!
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 220: Using hdik for attach
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 225: hdik output is: 
[SUCCESSIONLOG 1.3.8: 2019-09-07 06:56:17 +0000] Line 636: ERROR! Attaching image failed because hdik returned no output. Please reboot and try again.` This file is succession.logs , hope developer fix this problem soon. tks!

**Comment by Samgisaninja** [comment] 2019-09-07 17:19
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-09-07 17:19 UTC
