### ISSUE TITLE
Attaching image failed because Hdik returned no output

### ISSUE THREAD

**Issue by mclopes** [Samgisaninja/SuccessionRestore#65] opened 2019-09-27 16:45 UTC
I downloaded ipsw

Then I tried to restoreFS on uncover first to see if that would solve my issue. When I rejailbroke I got the error.

iPhone X on 12.4

**Comment by Samgisaninja** [comment] 2019-09-27 17:41
Duplicate of #48

**Closed as completed by Samgisaninja** 2019-09-27 17:41 UTC
