### ISSUE TITLE
xs max 12.4 is not working 

### ISSUE THREAD

**Issue by qin4** [Samgisaninja/SuccessionRestore#80] opened 2019-12-21 09:48 UTC
version 1.3 - 1.3.8 
usr/libexec/xpcproxy
Rebuilding usr
==========
version 1.4 - 1.4.4
mounting，please wait …

is long long time …

**Comment by Samgisaninja** [comment] 2019-12-21 20:42
Duplicate of #64 (which was already fixed, don't create issue reports for older versions, especially if the bug was already fixed)

Duplicate of #74

**Closed as completed by Samgisaninja** 2019-12-21 20:42 UTC
