### ISSUE TITLE
SuccessionRestore Mounting file system

### ISSUE THREAD

**Issue by efe-star** [Samgisaninja/SuccessionRestore#46] opened 2019-08-03 21:28 UTC
When I click on the message: "Mounting filesystem ... Tap OK to continue" nothing happens.
Iphone 8 Plus (GSM) Ios: 12.2

**Comment by Samgisaninja** [comment] 2019-08-03 21:48
Duplicate of #37

**Closed as completed by Samgisaninja** 2019-08-03 21:48 UTC
