### ISSUE TITLE
You don’t have permission to save the file “mnt1” in the folder “MobileSoftwareUpdate”

### ISSUE THREAD

**Issue by m1stadev** [Samgisaninja/SuccessionRestore#47] opened 2019-08-08 04:10 UTC
iPhone 5S, iOS 10.3.3, Meridian, latest Succession

I downloaded the latest version of Succession and ran it, but after downloading the IPSW, it gets to this and errors out. The only options I have changed from default is having an `orig-fs` snapshot be made (I did install Snappy). Is there any fix?
![Screenshot of error](https://user-images.githubusercontent.com/37033149/62674567-8aec7380-b968-11e9-905e-85de0d227f0d.png)

**Comment by m1stadev** [comment] 2019-08-08 16:16
Pastebin of the `succession.log`: https://pastebin.com/HgixFXpM

**Comment by Samgisaninja** [comment] 2019-08-11 20:53
Duplicate of #29

**Closed as completed by Samgisaninja** 2019-08-11 20:53 UTC
